# Generated by Django 4.0.3 on 2022-04-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maincategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20, unique=True)),
                ('Baseprice', models.IntegerField()),
                ('Discount', models.IntegerField(default=0)),
                ('Finalprice', models.IntegerField()),
                ('Color', models.CharField(max_length=20)),
                ('Size', models.CharField(max_length=10)),
                ('Description', models.TextField()),
                ('Stock', models.BooleanField(default=True)),
                ('Time', models.DateTimeField(auto_now=True)),
                ('Pic1', models.ImageField(upload_to='images')),
                ('Pic2', models.ImageField(upload_to='images/')),
                ('Pic3', models.ImageField(upload_to='images/')),
                ('Pic4', models.ImageField(upload_to='images/')),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stark.brand')),
                ('Maincat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stark.maincategory')),
                ('Subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stark.subcategory')),
            ],
        ),
    ]
