# Generated by Django 4.0.3 on 2022-04-24 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stark', '0002_rename_baseprice_product_baseprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='baseprice',
            new_name='Baseprice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='Color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='Discount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='finalprice',
            new_name='Finalprice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='maincat',
            new_name='Maincat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pic1',
            new_name='Pic1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pic2',
            new_name='Pic2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pic3',
            new_name='Pic3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pic4',
            new_name='Pic4',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='Size',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='Stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcat',
            new_name='Subcat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='time',
            new_name='Time',
        ),
    ]
