# Generated by Django 4.0.3 on 2022-04-24 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stark', '0003_rename_baseprice_product_baseprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Baseprice',
            new_name='baseprice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Discount',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Finalprice',
            new_name='finalprice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Maincat',
            new_name='maincat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Pic1',
            new_name='pic1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Pic2',
            new_name='pic2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Pic3',
            new_name='pic3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Pic4',
            new_name='pic4',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Stock',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Subcat',
            new_name='subcat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Time',
            new_name='time',
        ),
    ]
