# Generated by Django 4.0.3 on 2022-04-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stark', '0005_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='addressline1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='addressline2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='addressline3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
