# Generated by Django 4.0.4 on 2022-05-01 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stark', '0009_buyer_rename_baseprice_product_baseprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('products', models.CharField(max_length=30)),
                ('total', models.IntegerField()),
                ('shipping', models.IntegerField(default=0)),
                ('finalAmount', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Not Packed'), (2, 'Packed'), (3, 'Out for Delivery'), (4, 'Delivered')], default=1)),
                ('paymentStatus', models.IntegerField(choices=[(1, 'Pending'), (2, 'Done')], default=1)),
                ('mode', models.IntegerField(choices=[(1, 'COD'), (2, 'Net Banking')], default=1)),
                ('time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('orderId', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('paymentId', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('paymentsignature', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stark.buyer')),
            ],
        ),
    ]
